#disabled_rules:
# - line_length
# - type_body_length
# - function_body_length
# - file_length
# - cyclomatic_complexity

line_length:
  warning: 180
  error: 260
  
file_length:
  warning: 600
  error: 700
  
type_body_length:
  warning: 500
  error: 600

opt_in_rules:
 - force_unwrapping
 - implicitly_unwrapped_optional
  
analyzer_rules:
 - unused_import

identifier_name:
 excluded:
  - o
  - s
  - z
  - i
  - j
  - l
  - t
  - a
  - b
  - y
  - up
  - id
  - fx

nesting:
 type_level:
  warning: 2
# function_level:
#  warning: 10
